### ISSUE TITLE
Отметка мин

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/minesweeper#9]
Написать функцию, которая позволит для заданного поля поставить отметку о наличии мины.

**Comment by Nikita-90** [comment]
Возможно ли такое решение?

def mark_mine(x, y, flag, playing_field):
    """
    x, y -- from 'def input_coordinates():'
    flag  -- from 'def action(coords):'
    playing_field -- from 'def creating_playing_field():'
    """
    if flag == 'F':
        playing_field[x][y] = 'F'

**Comment by denyszamiatin** [comment]
я думаю, годится

2016-09-20 13:04 GMT+03:00 Nikita-90 notifications@github.com:
